CREATE DATABASE LOSTARKPROJECT;
USE LOSTARKPROJECT;


-- 멤버 테이블
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(50) PRIMARY KEY,
    MEMBER_PASSWD VARCHAR(255) NOT NULL,
    REGISTRATION_DATE DATE NOT NULL,
    REPRESENTATIVE_CHARACTER_NICKNAME VARCHAR(50) NOT NULL
);

-- 캐릭터 테이블
CREATE TABLE MEMBER_CHARACTER (
    CHARACTER_NICKNAME VARCHAR(50) PRIMARY KEY,
    SERVER_NAME VARCHAR(50),
    CHARACTER_CLASS VARCHAR(50),
    ITEM_LEVEL INT,
    ROSTER_LEVEL INT,
    MEMBER_ID VARCHAR(50),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 수집 테이블
CREATE TABLE COLLECTIBLE_POINT (
	MEMBER_ID VARCHAR(50),
    COLLECTABLE_TYPE_NAME VARCHAR(50),
    COLLECTED_POINT INT,
    COLLECTABLE_MAX_POINT INT,
    COLLECTED_POINT_TOTAL INT,
    COLLECTABLE_POINT_NAME VARCHAR(50) NOT NULL,
    IS_COLLECTED BOOLEAN DEFAULT FALSE,
    PRIMARY KEY(COLLECTABLE_TYPE_NAME, MEMBER_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 컨텐츠 테이블
CREATE TABLE CONTENT (
    CONTENT_ID INT PRIMARY KEY,
    CONTENT_NAME VARCHAR(100),
    CONTENT_ICON_LINK VARCHAR(255),
    MIN_ITEM_LEVEL INT,
    CONTENT_LOCATION VARCHAR(100),
    CONTENT_CATEGORY VARCHAR(50)
);

-- 알람 설정 테이블
CREATE TABLE ALARM (
    ALARM BOOLEAN DEFAULT FALSE,
    MEMBER_ID VARCHAR(50),
    CONTENT_ID INT,
    PRIMARY KEY (MEMBER_ID, CONTENT_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

-- 컨텐츠 시작시간
CREATE TABLE START_TIME (
    CONTENT_START_TIME DATETIME,
    CONTENT_ID INT,
    PRIMARY KEY (CONTENT_START_TIME, CONTENT_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

-- 보상 테이블
CREATE TABLE REWARD (
    CONTENT_ID INT,
    REWARD_ITEM_NAME VARCHAR(100),
    REWARD_ITEM_LEVEL INT,
    REWARD_ITEM_ICON_LINK VARCHAR(255),
    REWARD_ITEM_GRADE VARCHAR(50),
    PRIMARY KEY (CONTENT_ID, REWARD_ITEM_NAME, REWARD_ITEM_LEVEL),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

-- 멘토
CREATE TABLE MENTOR (
    MENTOR_MEMBER_ID VARCHAR(50),
    MENTOR_CONTENT_ID INT,
    MENTOR_DISCORD_ID VARCHAR(50),
    MENTOR_WANT_TO_SAY VARCHAR(255),
    PRIMARY KEY (MENTOR_MEMBER_ID, MENTOR_CONTENT_ID),
    FOREIGN KEY (MENTOR_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
    FOREIGN KEY (MENTOR_CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

-- 멘티 신청 컨텐츠
CREATE TABLE MENTEE (
    MENTEE_MEMBER_ID VARCHAR(50),
    MENTEE_CONTENT_ID INT,
    PRIMARY KEY (MENTEE_MEMBER_ID, MENTEE_CONTENT_ID),
    FOREIGN KEY (MENTEE_MEMBER_ID) REFERENCES MENTEE_APPLY(MENTEE_MEMBER_ID),
    FOREIGN KEY (MENTEE_CONTENT_ID) REFERENCES CONTENT(CONTENT_ID)
);

-- 멘티 신청
CREATE TABLE MENTEE_APPLY (
    MENTOR_MEMBER_ID VARCHAR(50),
    MENTEE_MEMBER_ID VARCHAR(50),
    MENTEE_WANT_TO_SAY VARCHAR(255),
    PRIMARY KEY (MENTOR_MEMBER_ID, MENTEE_MEMBER_ID),
    FOREIGN KEY (MENTOR_MEMBER_ID) REFERENCES MENTOR(MENTOR_MEMBER_ID),
    FOREIGN KEY (MENTEE_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 어드민
CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR(50) PRIMARY KEY,
    ADMIN_PASSWD VARCHAR(255)
);