CREATE DATABASE LOSTARKPROJECT;
USE LOSTARKPROJECT;



-- 멤버 테이블
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(50) PRIMARY KEY,
    MEMBER_PASSWD VARCHAR(255) NOT NULL,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT NOW(),
    REPRESENTATIVE_CHARACTER_NICKNAME VARCHAR(50) NOT NULL
);

-- 캐릭터 테이블
CREATE TABLE MEMBER_CHARACTER (
    CHARACTER_NICKNAME VARCHAR(50) PRIMARY KEY,
    SERVER_NAME VARCHAR(50) NOT NULL,
    CHARACTER_CLASS VARCHAR(50) NOT NULL,
    ITEM_LEVEL INT NOT NULL,
    ROSTER_LEVEL INT NOT NULL,
    MEMBER_ID VARCHAR(50),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- 수집 테이블
CREATE TABLE COLLECTIBLE_POINT (
    MEMBER_ID VARCHAR(50),
    COLLECTIBLE_TYPE_NAME VARCHAR(50) NOT NULL,
    COLLECTED_POINT INT NOT NULL,
    COLLECTIBLE_MAX_POINT INT NOT NULL,
    COLLECTIBLE_POINT_NAME VARCHAR(50) NOT NULL,
    COLLECTIBLE_ICON_LINK VARCHAR(255) NOT NULL,
    PRIMARY KEY(COLLECTIBLE_TYPE_NAME, COLLECTIBLE_POINT_NAME, MEMBER_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- 컨텐츠 테이블
CREATE TABLE CONTENT (
    CONTENT_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    CONTENT_NAME VARCHAR(100) NOT NULL,
    CONTENT_ICON_LINK VARCHAR(255) NOT NULL,
    MIN_ITEM_LEVEL INT NOT NULL,
    CONTENT_LOCATION VARCHAR(100) NOT NULL,
    CONTENT_CATEGORY VARCHAR(50) NOT NULL
);

-- 알람 설정 테이블
CREATE TABLE ALARM (
    MEMBER_ID VARCHAR(50),
    CONTENT_NUMBER INT,
    CONTENT_NAME VARCHAR(100),
    PRIMARY KEY (MEMBER_ID, CONTENT_NAME),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- 컨텐츠 시작시간
CREATE TABLE START_TIME (
    CONTENT_START_TIME DATETIME,
    CONTENT_NUMBER INT,
    PRIMARY KEY (CONTENT_START_TIME, CONTENT_NUMBER),
    FOREIGN KEY (CONTENT_NUMBER) REFERENCES CONTENT(CONTENT_NUMBER) ON DELETE CASCADE
);

-- 보상 테이블
CREATE TABLE REWARD (
    REWARD_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
    CONTENT_NUMBER INT NOT NULL,
    REWARD_ITEM_NAME VARCHAR(100) NOT NULL,
    REWARD_ITEM_LEVEL INT NOT NULL,
    REWARD_ITEM_ICON_LINK VARCHAR(255) NOT NULL,
    REWARD_ITEM_GRADE VARCHAR(50) NOT NULL,
    FOREIGN KEY (CONTENT_NUMBER) REFERENCES CONTENT(CONTENT_NUMBER) ON DELETE CASCADE
);

-- 멘토
CREATE TABLE MENTOR (
    MENTOR_MEMBER_ID VARCHAR(50),
    MENTOR_DISCORD_ID VARCHAR(50) NOT NULL,
    MENTOR_WANT_TO_SAY VARCHAR(255),
    PRIMARY KEY (MENTOR_MEMBER_ID),
    FOREIGN KEY (MENTOR_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- 멘토 컨텐츠 다중선택 위한 테이블
CREATE TABLE MENTOR_CONTENT (
    MENTOR_MEMBER_ID VARCHAR(50),
    MENTOR_CONTENT_ID VARCHAR(100),
    PRIMARY KEY (MENTOR_MEMBER_ID, MENTOR_CONTENT_ID),
    FOREIGN KEY (MENTOR_MEMBER_ID) REFERENCES MENTOR(MENTOR_MEMBER_ID) ON DELETE CASCADE
);


-- 멘티
CREATE TABLE MENTEE_APPLY (
    MENTOR_MEMBER_ID VARCHAR(50),
    MENTEE_MEMBER_ID VARCHAR(50),
    MENTEE_WANT_TO_SAY VARCHAR(255),
    PRIMARY KEY (MENTOR_MEMBER_ID, MENTEE_MEMBER_ID),
    FOREIGN KEY (MENTOR_MEMBER_ID) REFERENCES MENTOR(MENTOR_MEMBER_ID) ON DELETE CASCADE,
    FOREIGN KEY (MENTEE_MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

-- 멘티 신청 컨텐츠(멘토에게 전송되는 페이지)
CREATE TABLE MENTEE (
    MENTEE_MEMBER_ID VARCHAR(50),
    MENTEE_CONTENT_ID VARCHAR(100),
    PRIMARY KEY (MENTEE_MEMBER_ID, MENTEE_CONTENT_ID),
    FOREIGN KEY (MENTEE_MEMBER_ID) REFERENCES MENTEE_APPLY(MENTEE_MEMBER_ID) ON DELETE CASCADE
);

-- 어드민
CREATE TABLE ADMIN (
    ADMIN_ID VARCHAR(50) PRIMARY KEY,
    ADMIN_PASSWD VARCHAR(255)
);
